export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Load powerlevel10k config
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Aliases
alias ls="eza --icons"
alias ll="eza -lh --icons"
alias la="eza -lha --icons"
alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gl="git pull"

# Plugins
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
